---
# tasks file for osp-securitygroup
  - name: Allow SSH Connection to Bastion Host
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: bastion_sg 
      protocol: "{{ proto[0] }}"
      port_range_min: "{{ ports[0] }}"
      port_range_max: "{{ ports[0] }}" 
      remote_ip_prefix: "{{ ip[0] }}"
  - name:  Allow ICMP to Bastion
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: bastion_sg 
      protocol: "{{ proto[2] }}"
      remote_ip_prefix: "{{ ip[0] }}"
