---
# vars file for osp-securitygroup
cloud_name: ocpcloud
ip:
- 0.0.0.0/0
proto:
- tcp
- udp
- icmp
ports:
- 22
- 4789
- 53
- 8053
- 443
- 8443
- 10250
- 10010
- 2049
- 2379
- 2380
- 9000
- 9200
- 9300
